# Build backend binary file
FROM golang:1.25.1-alpine3.22 AS be-builder
ARG RELEASE_BUILD
ARG BUILD_PIPELINE
ARG CHECK_3RD_API
ARG SKIP_TESTS
ARG TARGETOS
ARG TARGETARCH
ENV RELEASE_BUILD=$RELEASE_BUILD
ENV BUILD_PIPELINE=$BUILD_PIPELINE
ENV CHECK_3RD_API=$CHECK_3RD_API
ENV SKIP_TESTS=$SKIP_TESTS
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH
WORKDIR /go/src/github.com/mayswind/ezbookkeeping
COPY . .
RUN docker/backend-build-pre-setup.sh
RUN apk add git gcc g++ libc-dev
RUN ./port_build.sh backend --no-lint --no-test

# Build frontend files
FROM --platform=$BUILDPLATFORM node:24.7.0-alpine3.22 AS fe-builder
ARG RELEASE_BUILD
ARG BUILD_PIPELINE
ENV RELEASE_BUILD=$RELEASE_BUILD
ENV BUILD_PIPELINE=$BUILD_PIPELINE
WORKDIR /go/src/github.com/mayswind/ezbookkeeping
COPY . .
RUN docker/frontend-build-pre-setup.sh
RUN apk add git
RUN ./port_build.sh frontend

# Package 
FROM alpine:3.22.1
ARG RELEASE_BUILD
ARG BUILD_PIPELINE
ARG TARGETARCH
ENV RELEASE_BUILD=$RELEASE_BUILD
ENV BUILD_PIPELINE=$BUILD_PIPELINE
WORKDIR /go/src/github.com/mayswind/ezbookkeeping
COPY --from=be-builder /go/src/github.com/mayswind/ezbookkeeping/ezbookkeeping ./ezbookkeeping
COPY --from=fe-builder /go/src/github.com/mayswind/ezbookkeeping/dist ./dist
COPY conf ./conf
COPY templates ./templates
COPY LICENSE .
COPY port_build.sh .
COPY package.json .
RUN apk add tar bash git
RUN ./port_build.sh package -a $TARGETARCH --no-rebuild

