name: Build for RISC-V Architecture

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install RISC-V cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-linux-gnu

      - name: Build backend for RISC-V 64
        run: |
          GOOS=linux GOARCH=riscv64 CGO_ENABLED=1 CC=riscv64-linux-gnu-gcc go build -ldflags "-s -w -X main.version=${GITHUB_REF_NAME#v}" -o ezbookkeeping-riscv64 ./ezbookkeeping.go

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Package for RISC-V 64
        run: |
          mkdir -p ezbookkeeping
          cp ezbookkeeping-riscv64 ezbookkeeping/
          cp -R dist public/
          cp -r conf templates public ezbookkeeping/
          tar -czf ezbookkeeping-${{ github.ref_name }}-linux-riscv64.tar.gz ezbookkeeping
          rm -rf ezbookkeeping

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezbookkeeping-${{ github.ref_name }}-linux-riscv64
          path: ezbookkeeping-${{ github.ref_name }}-linux-riscv64.tar.gz
          if-no-files-found: error

  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build-binary
    steps:
      - name: Download RISC-V 64 packaged files
        uses: actions/download-artifact@v4
        with:
          name: ezbookkeeping-${{ github.ref_name }}-linux-riscv64
          path: ./release-files

      - name: Publish Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release-files/*
          draft: false
